add trait command
AkrilliA/laravel-beyond pull request #76
Opened 2022-09-27 09:24 UTC by dimzeta

As https://github.com/regnerisch/laravel-beyond/issues/54 requested, I have created `beyond:make:trait` command, which is creates a simple trait in the domain namespace.

2022-09-27 10:16 UTC, alexgaal requested changes

2022-09-27 10:16 UTC, alexgaal commented on src/Commands/MakeTraitCommand.php
> +            $directory = $support ? 'Packages/Laravel/Traits' : 'Traits';
`Packages/Laravel/Traits` is not longer the correct directory. Please see https://github.com/regnerisch/laravel-beyond/blob/main/src/Commands/MakeMiddlewareCommand.php#L22 as reference.

2022-09-27 10:16 UTC, alexgaal commented on stubs/trait.support.stub
> +namespace Support\Packages\Laravel\Traits;
Please remove `Packages\Laravel` from namespace.

2022-09-27 10:16 UTC, alexgaal commented on tests/Commands/MakeTraitCommandTest.php
> +test('namespace is correct', function () {
We provide a function for that, please see https://github.com/regnerisch/laravel-beyond/blob/main/tests/Commands/MakeBuilderCommandTest.php as reference.

2022-09-27 10:16 UTC, alexgaal commented on tests/Commands/MakeTraitCommandTest.php
> +    expect($content)->toContain('namespace Support\Packages\Laravel\Traits;');
I'd suggest to use `toFileContains($string)` for this use case.

2022-09-27 10:16 UTC, alexgaal commented on tests/Commands/MakeTraitCommandTest.php
> +    expect($content)->toContain('trait HasActivationCodeTrait');
I'd suggest to use `toFileContains($string)` for this use case.

2022-09-27 10:16 UTC, alexgaal commented on tests/Commands/MakeTraitCommandTest.php
> +    expect($content)->toContain('trait HasActivationCodeTrait');
I'd suggest to use `toFileContains($string)` for this use case.

2022-09-27 11:41 UTC, regnerisch commented
I would expect traits to live only inside the `Support` namespace, as you can use them everywhere. See example below:

```php
trait Debug
{
    protected function log($exception)
    {
        // do something special for debug logging
    }
}
```

2022-09-27 12:38 UTC, dimzeta commented
I did the changes based on your comments.

2022-09-27 14:31 UTC, regnerisch requested changes

2022-09-27 14:31 UTC, regnerisch commented on src/Commands/MakeTraitCommand.php
>              $stub = $support ? 'trait.support.stub' : 'trait.stub';
Remove this line.

2022-09-27 14:31 UTC, regnerisch commented on src/Commands/MakeTraitCommand.php
>                  $stub,
Replace `$stub` with `trait.stub`

2022-09-27 14:34 UTC, regnerisch commented
You are close :)

I also want to say thank you, for your contribution! It's nice to see people helping us with this little project.

2022-09-27 17:08 UTC, dimzeta commented
This project is gold to me, so It's an honor to contribute on it!

If I understand correctly, it seems you don't want `Traits` in the `Domain` namespace, and only create them in `Support`.

In my case, I need to create a trait in the Domain, like this:

```php
<?php

namespace Domain\Authentication\Traits;

trait HasActivationCode
{
    // ...
}
```

And use it in my User model:

```php
<?php

namespace Domain\Users\Models;

use Domain\Authentication\Traits\HasActivationCode;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasActivationCode;

    // ...
}
```

I am not very experimented in DDD, so maybe this is not the proper way to do that 🤷

2022-09-28 20:26 UTC, regnerisch commented
Yes, I only want them to be created inside the `Support` namespace. 

Traits are properties and methods you can reuse in **every** class. It is quite unlikely you will create a trait which is reused in only one specific domain. So I would expect traits to be created inside the `Support` namespace to not violate separation by accident (e.g. using a trait of another domain)

We have two options here: Forcing creation inside one specific namespace, or remove the command to not force creation in one namespace. I prefer the former. You are always free to move your trait elsewhere.

2022-10-03 22:38 UTC, alexgaal approved these changes

2022-11-17 15:40 UTC, regnerisch approved these changes

2022-11-17 20:33 UTC, merged